tools:
  submit:
    signature: "submit"
    docstring: "submits when finished with the task"
    # Do not actually show the -f argument to the model, only
    # use it from the agent for submission after error
