tools:
  str_replace_editor:
    signature: |
      str_replace_editor <command> <path> [<view_range>]
    # This docstrings was taken from openhands:
    # https://github.com/All-Hands-AI/OpenHands/blob/main/openhands/agenthub/codeact_agent/function_calling.py
    docstring: >
      Custom tool for viewing files
      * State is persistent across command calls and discussions with the user
      * If `path` is a file, `view` displays the result of applying `cat -n`. If `path` is a directory, `view` lists non-hidden files and directories up to 2 levels deep
      * If a `command` generates a long output, it will be truncated and marked with `<response clipped>`
    arguments:
      - name: command
        type: string
        description: "The commands to run. The only allowed option is: `view`."
        required: true
        enum: ["view"]
      - name: path
        type: string
        description: "Absolute path to file or directory, e.g. `/testbed/file.py` or `/testbed`."
        required: true
      - name: view_range
        type: array
        items:
          type: integer
        description: "Optional parameter of `view` command when `path` points to a file. If none is given, the full file is shown. If provided, the file will be shown in the indicated line number range, e.g. [11, 12] will show lines 11 and 12. Indexing at 1 to start. Setting `[start_line, -1]` shows all lines from `start_line` to the end of the file."
        required: false
        argument_format: "--view_range {{value|join(' ')}}"
state_command: "_state_anthropic"
